"""Update place. up_gourmet_check field

Revision ID: 19fc258883c3
Revises: 2b40a80557c2
Create Date: 2023-03-25 20:14:16.454876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fc258883c3'
down_revision = '2b40a80557c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('up_gorumet_check', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'up_gorumet_check')
    # ### end Alembic commands ###
