"""Update place. up_gourmet_check field spell

Revision ID: 1eb84c439b9b
Revises: 19fc258883c3
Create Date: 2023-03-25 20:33:13.203747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb84c439b9b'
down_revision = '19fc258883c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('up_gourmet_check', sa.Boolean(), nullable=False))
    op.drop_column('place', 'up_gorumet_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('up_gorumet_check', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('place', 'up_gourmet_check')
    # ### end Alembic commands ###
