"""Update place. Card without service options

Revision ID: 219f9174d87d
Revises: 8d0b44836fad
Create Date: 2023-03-23 22:22:27.220094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219f9174d87d'
down_revision = '8d0b44836fad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('formatted_address', sa.String(length=80), nullable=False))
    op.add_column('place', sa.Column('formatted_phone_number', sa.String(length=20), nullable=False))
    op.add_column('place', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('place', sa.Column('types', sa.String(length=100), nullable=False))
    op.add_column('place', sa.Column('editorial_summary', sa.String(length=200), nullable=False))
    op.drop_column('place', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('place', 'editorial_summary')
    op.drop_column('place', 'types')
    op.drop_column('place', 'name')
    op.drop_column('place', 'formatted_phone_number')
    op.drop_column('place', 'formatted_address')
    # ### end Alembic commands ###
