"""Update place. Integers and float

Revision ID: 2b40a80557c2
Revises: 219f9174d87d
Create Date: 2023-03-23 22:26:54.085110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b40a80557c2'
down_revision = '219f9174d87d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('place', sa.Column('user_ratings_total', sa.Integer(), nullable=False))
    op.add_column('place', sa.Column('price_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'price_level')
    op.drop_column('place', 'user_ratings_total')
    op.drop_column('place', 'rating')
    # ### end Alembic commands ###
