"""Update place. location

Revision ID: 3f2dd96e3c4c
Revises: 1eb84c439b9b
Create Date: 2023-03-26 12:11:37.836420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2dd96e3c4c'
down_revision = '1eb84c439b9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('postal_code', sa.Integer(), nullable=False))
    op.add_column('place', sa.Column('town', sa.String(length=50), nullable=False))
    op.add_column('place', sa.Column('province', sa.String(length=50), nullable=False))
    op.add_column('place', sa.Column('location', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'location')
    op.drop_column('place', 'province')
    op.drop_column('place', 'town')
    op.drop_column('place', 'postal_code')
    # ### end Alembic commands ###
