"""Update place. Add address

Revision ID: 8d0b44836fad
Revises: 5847b193d9f9
Create Date: 2023-03-23 22:01:28.817639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0b44836fad'
down_revision = '5847b193d9f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('address', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'address')
    # ### end Alembic commands ###
